version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - .:/app
    restart: unless-stopped

  # Add other services as needed (database, cache, etc.)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"



